### ISSUE TITLE
 No module named 'src.configs' after pip install , Ubuntu 22.04 LTS , Python 3.10.12

### ISSUE THREAD

**Issue by kleozzy** [hansmach1ne/LFImap#112]
Ubuntu 22.04 LTS ,
Python 3.10.12

lfimap -h
Traceback (most recent call last):
  File "/home/user/.local/bin/lfimap", line 5, in <module>
    from lfimap.lfimap import main
  File "/home/user/.local/lib/python3.10/site-packages/lfimap/lfimap.py", line 21, in <module>
    from src.configs import config
ModuleNotFoundError: No module named 'src.configs'

**Comment by kleozzy** [comment]
installing with pipx fixes this , might be some python updates that broke this.

**Comment by hansmach1ne** [comment]
@kleozzy Thanks for taking interest in LFImap.

I will try to reproduce this issue, however could you tell me how did you install lfimap prior to running it. Was it manully with git clone or with pip install?

**Comment by kleozzy** [comment]
Through pip initially.

**Comment by mastercho** [comment]
> installing with pipx fixes this , might be some python updates that broke this.

Tried and doesn't solve it, still fails just as normal pip

**Comment by hansmach1ne** [comment]
@mastercho @kleozzy  Ah, shoot, yeah, it's likely an error from recent project structure updates.  I will try to make some time this weekend and try to solve it if it's a simpler fix. Sorry for the delay, have been busy lately. :(

**Comment by hansmach1ne** [comment]
@mastercho or @kleozzy Tried to debug what is wrong and to me it seems that `pip install lfimap` works fine. I tried installing it freshly on kali linux 2024.2..

```
pip install lfimap  
Defaulting to user installation because normal site-packages is not writeable
Collecting lfimap
  Downloading lfimap-0.1.4-py3-none-any.whl.metadata (7.7 kB)
Collecting argparse (from lfimap)
  Using cached argparse-1.4.0-py2.py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: bs4 in ./.local/lib/python3.11/site-packages (from lfimap) (0.0.2)
Requirement already satisfied: pybase64 in ./.local/lib/python3.11/site-packages (from lfimap) (1.3.2)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from lfimap) (2.31.0)
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from lfimap) (1.26.18)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from bs4->lfimap) (4.12.3)
Requirement already satisfied: soupsieve>1.2 in /usr/lib/python3/dist-packages (from beautifulsoup4->bs4->lfimap) (2.5)
Downloading lfimap-0.1.4-py3-none-any.whl (162 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.5/162.5 kB 234.1 kB/s eta 0:00:00
Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Installing collected packages: argparse, lfimap
  WARNING: The script lfimap is installed in '/home/kali/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed argparse-1.4.0 lfimap-0.1.4

─(kali㉿kali)-[~]
└─$ /home/kali/.local/bin/lfimap -h

  _      ______ _____                       
 | |    |  ____|_   _|                      
 | |    | |__    | |  _ __ ___   __ _ _ __  
 | |    |  __|   | | | '_ ` _ \ / _` | '_ \ 
 | |____| |     _| |_| | | | | | (_| | |_) |
 |______|_|    |_____|_| |_| |_|\__,_| .__/ 
                                     | |    
                                     |_|    

                                - by @h4nsmach1ne
                                
                                usage: lfimap [-U [url]] [-F [urlfile]] [-R [reqfile]] [-C <cookie>] [-D <data>] [-H <header>]
              [-M <method>] [-P <proxy>] [--useragent <agent>] [--referer <referer>]
              [--placeholder <name>] [--delay <milis>] [--max-timeout <seconds>]
              [--http-ok <number>] [--csrf-param <param>] [--csrf-method <method>]
              [--csrf-url <url>] [--csrf-data <data>] [--second-method <method>]
              [--second-url <url>] [--second-data <data>] [--force-ssl] [--no-stop] [-f] [-i] [-d]
              [-e] [-t] [-r] [-c] [-file] [-heur] [-a] [-n <U|B>] [-q] [-x] [--lhost <lhost>]
              [--lport <lport>] [--callback <hostname>] [-wT <path>] [--use-long] [--log <file>]
              [-nc] [-v] [-h]
```

I suspect this could be the pypi config issue. Can you please execute the: `ls -alR /home/user/.local/lib/python3.10/site-packages/lfimap`. The src folder must exist inside, but according to the error it cannot reach the .py scripts inside it.

**Comment by kleozzy** [comment]
its sorted now thanks
